import { Toaster } from "@/components/ui/toaster";
import BarraLateral from "./components/barra-lateral";
import NavStart from "./components/nav-start";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StartLayout({ children }) {
  return (
    <>
      <NavStart />
      <div className="grid xl:grid-cols-[1fr_4fr] xl:px-0 sm:px-10 px-3">
        <BarraLateral />
        {children}
      </div>
      <Toaster />
    </>
  );
}
